### PR TITLE
Fixed http api error.

### LINKED ISSUE #597: PR #564 breaks Http API
Launched broker with flag http, and run a sub client.
```
$ ./nanomq/nanomq broker start --http
$ mosquitto_sub -t abc
```
then use curl post request
```
curl --location --request POST 'http://localhost:8081/api/v1' \
--header 'Authorization: Basic YWRtaW46cHVibGlj' \
--header 'Content-Type: application/json' \
--data-raw '{
    "req": 4,
    "seq": 111
}'
```
cause broker heap-buffer-overflow
```
=================================================================
==2062==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300000a978 at pc 0x00010a2f8a85 bp 0x7000104fc770 sp 0x7000104fc768
READ of size 8 at 0x60300000a978 thread T26
    #0 0x10a2f8a84 in get_subscriptions rest_api.c:490
    #1 0x10a2fd0d4 in process_request rest_api.c:325
    #2 0x10a3032bd in inproc_server web_server.c:360
    #3 0x10a38abc7 in nni_thr_wrap thread.c:94
    #4 0x10a3a9bec in nni_plat_thr_main posix_thread.c:266
    #5 0x7fff6b485108 in _pthread_start+0x93 (libsystem_pthread.dylib:x86_64+0x6108)
    #6 0x7fff6b480b8a in thread_start+0xe (libsystem_pthread.dylib:x86_64+0x1b8a)

0x60300000a978 is located 0 bytes to the right of 24-byte region [0x60300000a960,0x60300000a978)
allocated by thread T11 here:
    #0 0x10a5ee17d in wrap_malloc+0x9d (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x4917d)
    #1 0x10a2bb2dd in zmalloc zmalloc.c:50
    #2 0x10a293185 in dbtree_new_ctxt mqtt_db.c:30
    #3 0x10a296e90 in dbtree_client_new mqtt_db.c:362
    #4 0x10a296d3d in dbtree_insert_client mqtt_db.c:720
    #5 0x10a2f2f62 in sub_ctx_handle sub_handler.c:309
    #6 0x10a30b67d in server_cb broker.c:354
    #7 0x10a38682f in nni_taskq_thread taskq.c:50
    #8 0x10a38abc7 in nni_thr_wrap thread.c:94
    #9 0x10a3a9bec in nni_plat_thr_main posix_thread.c:266
    #10 0x7fff6b485108 in _pthread_start+0x93 (libsystem_pthread.dylib:x86_64+0x6108)
    #11 0x7fff6b480b8a in thread_start+0xe (libsystem_pthread.dylib:x86_64+0x1b8a)

Thread T26 created by T0 here:
    #0 0x10a5e831a in wrap_pthread_create+0x5a (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x4331a)
    #1 0x10a3a995d in nni_plat_thr_init posix_thread.c:279
    #2 0x10a38a86c in nni_thr_init thread.c:121
    #3 0x10a446fba in nng_thread_create platform.c:55
    #4 0x10a303662 in start_rest_server web_server.c:431
    #5 0x10a315d9f in broker_start broker.c:1243
    #6 0x10a2e81cc in main nanomq.c:221
    #7 0x7fff6b280cc8 in start+0x0 (libdyld.dylib:x86_64+0x1acc8)

Thread T11 created by T0 here:
    #0 0x10a5e831a in wrap_pthread_create+0x5a (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x4331a)
    #1 0x10a3a995d in nni_plat_thr_init posix_thread.c:279
    #2 0x10a38a86c in nni_thr_init thread.c:121
    #3 0x10a3864b4 in nni_taskq_init taskq.c:95
    #4 0x10a387a04 in nni_taskq_sys_init taskq.c:284
    #5 0x10a361edc in nni_init_helper init.c:35
    #6 0x10a3aa019 in nni_plat_init posix_thread.c:422
    #7 0x10a361ebf in nni_init init.c:58
    #8 0x10a446f38 in nng_thread_create platform.c:49
    #9 0x10a303662 in start_rest_server web_server.c:431
    #10 0x10a315d9f in broker_start broker.c:1243
    #11 0x10a2e81cc in main nanomq.c:221
    #12 0x7fff6b280cc8 in start+0x0 (libdyld.dylib:x86_64+0x1acc8)

SUMMARY: AddressSanitizer: heap-buffer-overflow rest_api.c:490 in get_subscriptions
Shadow bytes around the buggy address:
  0x1c06000014d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c06000014e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c06000014f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0600001500: fa fa fd fd fd fa fa fa fd fd fd fd fa fa fd fd
  0x1c0600001510: fd fd fa fa 00 00 00 00 fa fa 00 00 00 fa fa fa
=>0x1c0600001520: 00 00 00 00 fa fa 00 00 00 00 fa fa 00 00 00[fa]
  0x1c0600001530: fa fa fd fd fd fa fa fa 00 00 00 fa fa fa 00 00
  0x1c0600001540: 00 fa fa fa 00 00 00 00 fa fa fd fd fd fa fa fa
  0x1c0600001550: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0600001560: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0600001570: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2062==ABORTING
[1]    2062 abort      ./nanomq/nanomq broker start --http
```

### PR DESCRIPTION
**Pull request by lee-emqx**
fixed #597

### CODE REVIEW

File: nanomq/rest_api.c [hunk 1]
```diff
@@ -433,15 +433,30 @@ get_subscriptions(cJSON *data, http_msg *msg, uint64_t sequence)
...
+		}
+		client_ctx *ctxt =  db_ctxt->ctx;
 
 		cJSON *data_info_elem;
 		data_info_elem = cJSON_CreateObject();
 		cJSON_AddItemToArray(data_info, data_info_elem);
-		const uint8_t *cid = conn_param_get_clientid(ctxt->cparam);
-		cJSON_AddStringToObject(
-		    data_info_elem, "client_id", (char *) cid);
+		if (ctxt->cparam) {
```
Comment (JaylinYu) [inline nanomq/rest_api.c:448]: still got potential data racing condition

Comment (JaylinYu) [inline nanomq/rest_api.c:448]: no defensive programming

**Review by JaylinYu — APPROVED** [review]
